services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: .
          target: /home/node/dockerode
        - action: rebuild
          path: package-lock.json
